package fr.coriolis.checker.core;

import java.util.ArrayList;

public class ValidationResult {
	private static final String BLANK_MESSAGE = new String("");

	private ArrayList<String> warnings;
	private ArrayList<String> errors;
	public static String lastMessage = BLANK_MESSAGE;

	public ValidationResult() {
		errors = new ArrayList<String>();
		warnings = new ArrayList<String>();
	}

	/** Clear the errors */
	public void clearFormatErrors() {
		if (errors != null) {
			errors.clear();
		}
	}

	/** Clear the warnings */
	public void clearFormatWarnings() {
		if (warnings != null) {
			warnings.clear();
		}
	}

	/** Retrieve the error descriptions for errors found during file checking */
	public ArrayList<String> getErrors() {
		return new ArrayList<String>(errors);
	}

	/** Retrieve the error descriptions for errors found during file checking */
	public ArrayList<String> getWarnings() {
		return new ArrayList<String>(warnings);
	}

	public void addError(String errorStr) {
		errors.add(errorStr);
	}

	public void addWarning(String warningStr) {
		warnings.add(warningStr);
	}

	/**
	 * Retrieve the number of format errors found during file checking
	 * 
	 * @returns number of file errors (0 = no errors)
	 */
	public int nFormatErrors() {
		return errors.size();
	}

	/**
	 * Retrieve the number of format warnings found during file checking
	 * 
	 * @returns number of file warnings (0 = no warnings)
	 */
	public int nFormatWarnings() {
		return warnings.size();
	}

	/** Retrieve the most recent error message generated by a method */
	public static String getMessage() {
		return new String(lastMessage);
	}

	public boolean isValid() {
		if (errors.size() == 0) {
			return true;
		} else {
			return false;
		}
	}

}