name: Image build

on:
  push:
    branches:
      # Run on our main branch
      - main
      - develop
    paths:
      - file_checker_exec/**
      - file_checker_spec/**
      - Dockerfile
  pull_request:
    # Run for any pull requests
    paths:
      - file_checker_exec/**
      - file_checker_spec/**
      - Dockerfile
  release:
    types: [created]
    

jobs:
  container-image-build:    
    uses: ./.github/workflows/component-container-image.yml
    with:
      context: .
      image-path: ghcr.io/OneArgo/ArgoFormatChecker/app